import "./globals.css";
import { Inter } from "next/font/google";
import HeaderLayout from "./headerLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {children} */}
        <div className="w-full mx-auto max-w-lg">
          <HeaderLayout> {children} </HeaderLayout>
        </div>
      </body>
    </html>
  );
}
